version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    volumes:
      - ./redminedt:/var/lib/redminedt
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysqldt:/var/lib/mysqldt
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine